import type { UserSettings } from './types'

export const SUPPORTED_LANGUAGES = [
  { code: 'auto', name: '自动检测' },
  { code: 'zh-CN', name: '中文（简体）' },
  { code: 'zh-TW', name: '中文（繁体）' },
  { code: 'en', name: '英语' },
  { code: 'ja', name: '日语' },
  { code: 'ko', name: '韩语' },
  { code: 'fr', name: '法语' },
  { code: 'de', name: '德语' },
  { code: 'es', name: '西班牙语' },
  { code: 'it', name: '意大利语' },
  { code: 'pt', name: '葡萄牙语' },
  { code: 'ru', name: '俄语' },
  { code: 'ar', name: '阿拉伯语' },
]

export const ENGINE_INFO = {
  google: {
    name: 'Google 翻译',
    description: '速度快，免费额度充裕',
    icon: '🌐',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://cloud.google.com/translate/docs',
  },
  deepl: {
    name: 'DeepL',
    description: '欧洲语言翻译质量最佳',
    icon: '🔵',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://www.deepl.com/pro-api',
  },
  deepseek: {
    name: 'DeepSeek',
    description: '中文理解极佳，成本最低',
    icon: '🚀',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://platform.deepseek.com',
  },
  openai: {
    name: 'OpenAI GPT',
    description: '综合质量最高，支持上下文理解',
    icon: '✨',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://platform.openai.com',
  },
  baidu: {
    name: '百度翻译',
    description: '国内访问稳定',
    icon: '🔴',
    requiresKey: true,
    keyLabel: 'APP ID + 密钥',
    docsUrl: 'https://fanyi-api.baidu.com',
  },
  local: {
    name: '本地模型',
    description: '完全离线，无需 API Key',
    icon: '💻',
    requiresKey: false,
    keyLabel: '',
    docsUrl: 'https://ollama.ai',
  },
  qwen: {
    name: '通义千问',
    description: '阿里云大模型，中文理解优秀',
    icon: '🟣',
    requiresKey: true,
    keyLabel: 'DashScope API Key',
    docsUrl: 'https://dashscope.aliyun.com',
  },
  minimax: {
    name: 'MiniMax',
    description: '国产大模型，长文本表现优秀',
    icon: '🌊',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://platform.minimaxi.com',
  },
  kimi: {
    name: 'Kimi',
    description: '月之暗面，长上下文理解能力强',
    icon: '🌙',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://platform.moonshot.cn',
  },
  glm: {
    name: '智谱 GLM',
    description: '清华智谱，学术场景友好',
    icon: '🔷',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://bigmodel.cn',
  },
  gemini: {
    name: 'Google Gemini',
    description: 'Google 最新多模态大模型',
    icon: '💎',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://ai.google.dev',
  },
  grok: {
    name: 'Grok',
    description: 'xAI 出品，推理能力强',
    icon: '⚡',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://docs.x.ai',
  },
  claude: {
    name: 'Claude',
    description: 'Anthropic 出品，人文理解极佳',
    icon: '🧡',
    requiresKey: true,
    keyLabel: 'API Key',
    docsUrl: 'https://console.anthropic.com',
  },
  doubao: {
    name: '豆包',
    description: '字节跳动大模型，国内访问稳定',
    icon: '🫘',
    requiresKey: true,
    keyLabel: 'API Key（火山方舟）',
    docsUrl: 'https://console.volcengine.com/ark',
  },
} as const

export const DEFAULT_SETTINGS: UserSettings = {
  engines: {
    google: { id: 'google', name: 'Google 翻译', enabled: false },
    deepl: { id: 'deepl', name: 'DeepL', enabled: false },
    deepseek: { id: 'deepseek', name: 'DeepSeek', enabled: false },
    openai: { id: 'openai', name: 'OpenAI GPT', enabled: false },
    baidu: { id: 'baidu', name: '百度翻译', enabled: false },
    local: { id: 'local', name: '本地模型', enabled: false },
    qwen:    { id: 'qwen',    name: '通义千问',     enabled: false },
    minimax: { id: 'minimax', name: 'MiniMax',       enabled: false },
    kimi:    { id: 'kimi',    name: 'Kimi',          enabled: false },
    glm:     { id: 'glm',     name: '智谱 GLM',      enabled: false },
    gemini:  { id: 'gemini',  name: 'Google Gemini', enabled: false },
    grok:    { id: 'grok',    name: 'Grok',          enabled: false },
    claude:  { id: 'claude',  name: 'Claude',        enabled: false },
    doubao:  { id: 'doubao',  name: '豆包',          enabled: false },
  },
  activeEngine: 'deepseek',
  translateMode: 'bilingual',
  sourceLang: 'auto',
  targetLang: 'zh-CN',
  autoTranslatePdf: false,
  autoTranslatePage: false,
  excludedDomains: [],
  fontSizeScale: 0.9,
  showOriginalOnHover: true,
  preserveFormulas: true,
  preserveCitations: true,
  theme: 'system',
  showFloatingPanel: false,
}

export const STORAGE_KEYS = {
  SETTINGS: 'tongwen_settings',
  USAGE: 'tongwen_usage',
  SUBSCRIPTION: 'tongwen_subscription',
} as const
